// GENERATED by tools/gen_params.py — do not edit by hand.
// Source of truth: the AUv3 Parameters.swift. Re-run the script to sync.
#pragma once
#include <cstdint>

enum class HCUnit { Generic, Indexed, Boolean, Seconds, Hertz, Milliseconds, LinearGain, SemiTones, Decibels };

struct HCParamSpec {
    uint32_t    id;          // == AU parameter address
    const char* identifier;
    const char* title;
    const char* groupId;
    const char* groupName;
    HCUnit      unit;
    float       minValue;
    float       maxValue;
    float       defaultValue;
};

static constexpr int kHCParamCount = 47;

static constexpr HCParamSpec kHCParams[kHCParamCount] = {
    { 0, "inputGain", "Input Gain", "global", "Global", HCUnit::LinearGain, 0.0f, 4.0f, 1.0f },
    { 1, "outputGain", "Output Gain", "global", "Global", HCUnit::LinearGain, 0.0f, 4.0f, 1.0f },
    { 12, "irNormalize", "IR Normalize", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 1.0f },
    { 3, "eqBand0", "EQ 80Hz", "global", "Global", HCUnit::Decibels, -12.0f, 12.0f, 0.0f },
    { 4, "eqBand1", "EQ 250Hz", "global", "Global", HCUnit::Decibels, -12.0f, 12.0f, 0.0f },
    { 5, "eqBand2", "EQ 800Hz", "global", "Global", HCUnit::Decibels, -12.0f, 12.0f, 0.0f },
    { 6, "eqBand3", "EQ 3.2KHz", "global", "Global", HCUnit::Decibels, -12.0f, 12.0f, 0.0f },
    { 7, "eqBand4", "EQ 8KHz", "global", "Global", HCUnit::Decibels, -12.0f, 12.0f, 0.0f },
    { 8, "reverbDecay", "Reverb Decay", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 0.5f },
    { 10, "reverbSize", "Reverb Size", "global", "Global", HCUnit::Generic, 0.5f, 2.0f, 1.0f },
    { 11, "reverbPreDelay", "Reverb PreDelay", "global", "Global", HCUnit::Milliseconds, 0.0f, 100.0f, 0.0f },
    { 9, "reverbBlend", "Reverb Wet", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 13, "reverbTone", "Reverb Tone", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 0.7f },
    { 14, "reverbPreAmp", "Reverb Pre-Amp", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 15, "eqPostAmp", "EQ Post-Amp", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 16, "reverbGate", "Reverb Gate", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 17, "stereoMode", "Stereo", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 18, "inputPad", "Input Pad", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 19, "invertR", "Invert R", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 20, "channelLink", "NAM Link", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 1.0f },
    { 23, "volLink", "Volume Link", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 1.0f },
    { 21, "inputGainR", "Input Gain R", "global", "Global", HCUnit::LinearGain, 0.0f, 4.0f, 1.0f },
    { 22, "outputGainR", "Output Gain R", "global", "Global", HCUnit::LinearGain, 0.0f, 4.0f, 1.0f },
    { 24, "delayTime", "Delay Time", "global", "Global", HCUnit::Milliseconds, 20.0f, 2000.0f, 350.0f },
    { 25, "delayFeedback", "Delay Feedback", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 0.35f },
    { 26, "delayTone", "Delay Tone", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 0.7f },
    { 27, "delayMix", "Delay Wet", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 28, "delaySync", "Delay Sync", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 29, "delayDivision", "Delay Division", "global", "Global", HCUnit::Indexed, 0.0f, 6.0f, 1.0f },
    { 30, "delayPingPong", "Delay Ping-Pong", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 31, "delayTape", "Delay Tape", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 32, "delayDuck", "Delay Duck", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 33, "delayPlacement", "Delay Placement", "global", "Global", HCUnit::Indexed, 0.0f, 2.0f, 2.0f },
    { 34, "delayOscillate", "Delay Oscillate", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 35, "delayOscCC", "Delay Osc CC", "global", "Global", HCUnit::Generic, 0.0f, 127.0f, 27.0f },
    { 36, "morphEnable", "Morph Enable", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 37, "morphSource", "Morph Source", "global", "Global", HCUnit::Indexed, 0.0f, 1.0f, 0.0f },
    { 38, "morphDepth", "Morph Depth", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 0.75f },
    { 39, "morphThreshold", "Morph Threshold", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 0.35f },
    { 40, "morphSensitivity", "Morph Sensitivity", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 0.5f },
    { 41, "morphAttack", "Morph Attack", "global", "Global", HCUnit::Milliseconds, 1.0f, 200.0f, 5.0f },
    { 42, "morphRelease", "Morph Release", "global", "Global", HCUnit::Milliseconds, 10.0f, 1000.0f, 120.0f },
    { 43, "morphInvert", "Morph Invert", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 44, "morphManual", "Morph Manual", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 45, "morphTargetAmp", "Morph Target Amp", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 1.0f },
    { 46, "morphTargetIR", "Morph Target IR", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 1.0f },
    { 47, "inputCalibration", "Input Cal", "global", "Global", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
};
