import Foundation

/// The palette a native patcher draws from, and the ASL each of its entries
/// lowers to.
///
/// Generated by `editor/src/materialCatalog.ts` from the web patcher's own
/// catalog and shipped as `material-catalog.json` inside this package. It is
/// not hand-maintained and must not be edited: `npm run fixtures:materials`
/// rewrites it, and an editor test rebuilds it in memory and fails when the
/// checked-in file differs.
///
/// ## Why the graphs travel as data
///
/// Every material is an ASL graph built once, in JavaScript, by a builder
/// function. Those builders are the 109 places a second implementation would
/// have to be written and then kept in step forever. A built graph, by
/// contrast, is plain data, and it does not depend on parameter values:
/// `AudioMaterial` assigns `this.graph` in its constructor and `setParam`
/// writes only `paramValues`. So one serialized graph per kind plus a value
/// map is everything `flattenPatch` needs to splice, and the thing that could
/// drift is a generated file with a test on it rather than a second codebase.
public struct MaterialCatalog: Decodable, Sendable {
    public let version: Int
    public let io: PatchIoKinds
    public let tools: [CatalogToolEntry]
    public let kernels: [CatalogKernelEntry]
    public let materials: [CatalogMaterialEntry]

    private enum CodingKeys: String, CodingKey {
        case version, io, tools, kernels, materials
    }

    private let materialsByKind: [String: CatalogMaterialEntry]
    private let toolsByKind: [String: CatalogToolEntry]
    private let kernelsByKind: [String: CatalogKernelEntry]

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        version = try container.decode(Int.self, forKey: .version)
        io = try container.decode(PatchIoKinds.self, forKey: .io)
        tools = try container.decode([CatalogToolEntry].self, forKey: .tools)
        kernels = try container.decode([CatalogKernelEntry].self, forKey: .kernels)
        materials = try container.decode([CatalogMaterialEntry].self, forKey: .materials)
        materialsByKind = Dictionary(uniqueKeysWithValues: materials.map { ($0.kind, $0) })
        toolsByKind = Dictionary(uniqueKeysWithValues: tools.map { ($0.kind, $0) })
        kernelsByKind = Dictionary(uniqueKeysWithValues: kernels.map { ($0.kind, $0) })
        // Walked once here rather than per cable: an audit asks this of every
        // connection in a patch, and the answer cannot change after decoding.
        readParams = Dictionary(
            uniqueKeysWithValues: materials.map { ($0.kind, $0.paramsTheGraphReads) }
        )
    }

    private let readParams: [String: Set<String>]

    /// Whether a cable into this inlet reaches anything.
    ///
    /// One rule, and it is `flattenPatch`'s rule read backwards. Flatten
    /// lowers a cable into a value and then rewrites the material's graph,
    /// replacing every `param` node of that name with it. A name the graph
    /// never reads has no node to replace, so the value is built and thrown
    /// away: the cable is in the document, the patch validates, the graph
    /// compiles, and the sound does not change.
    ///
    /// That is how the ADSR came to have a `note` jack and the two spatial
    /// modules five position jacks. Derived rather than listed, because a list
    /// goes stale the first time somebody edits a material's graph.
    ///
    /// A host tool is judged by its declared jacks instead: Master, Line,
    /// Keyboard and the rest are resolved by flatten itself and have no
    /// material graph to read. Answering an unconditional true for them was
    /// wrong in a way worth recording, because it does not look wrong: it made
    /// Master appear to accept a `reset`, so the audit reported that the
    /// output was not starting with the song.
    public func canReceiveCable(kind: String, inlet: String) -> Bool {
        if isHostTool(kind) { return jacks(kind)?.inputs.contains(inlet) == true }
        guard let material = material(kind) else { return false }
        return material.isAudioInlet(inlet) || readParams[kind]?.contains(inlet) == true
    }

    public static func decode(_ data: Data) throws -> MaterialCatalog {
        let catalog = try JSONDecoder().decode(MaterialCatalog.self, from: data)
        guard catalog.version == 1 else {
            // Refuse rather than run the half we recognise. The same rule
            // `ScenePlan.decode` follows, for the same reason: a document a
            // build does not understand is not a document to guess at.
            throw ASLCompileError(
                "material-catalog.json is version \(catalog.version); this build executes version 1."
            )
        }
        return catalog
    }

    /// The catalog shipped inside this package.
    ///
    /// Loaded once and held: it is ~170 KB of JSON and a patcher asks for it
    /// on every keystroke in the palette search field.
    public static func bundled() throws -> MaterialCatalog {
        if let cached = bundledCache.value { return cached }
        guard let url = Bundle.module.url(forResource: "material-catalog", withExtension: "json") else {
            throw ASLCompileError(
                "material-catalog.json is not in the CrateASL resource bundle. "
                    + "Run `npm run fixtures:materials` and check Package.swift still copies Resources."
            )
        }
        let catalog = try decode(try Data(contentsOf: url))
        bundledCache.value = catalog
        return catalog
    }

    private static let bundledCache = Cached()

    private final class Cached: @unchecked Sendable {
        private let lock = NSLock()
        private var stored: MaterialCatalog?
        var value: MaterialCatalog? {
            get { lock.lock(); defer { lock.unlock() }; return stored }
            set { lock.lock(); stored = newValue; lock.unlock() }
        }
    }

    public func material(_ kind: String) -> CatalogMaterialEntry? { materialsByKind[kind] }
    public func tool(_ kind: String) -> CatalogToolEntry? { toolsByKind[kind] }
    public func kernel(_ kind: String) -> CatalogKernelEntry? { kernelsByKind[kind] }

    /// Whether a kind is host I/O rather than DSP: the six kinds flatten
    /// resolves itself instead of looking up a Material.
    public func isHostTool(_ kind: String) -> Bool { io.contains(kind) }

    /// Jacks for any palette kind, whichever half it lives in. A patcher
    /// draws a node before it knows whether that node can run.
    public func jacks(_ kind: String) -> CatalogJacks? {
        if let material = materialsByKind[kind] {
            return CatalogJacks(
                inputs: material.inputs, outputs: material.outputs,
                inputLabels: material.inputLabels, outputLabels: material.outputLabels,
                audioInputs: Set(material.audioInputs)
            )
        }
        if let tool = toolsByKind[kind] {
            return CatalogJacks(
                inputs: tool.inputs, outputs: tool.outputs,
                inputLabels: tool.inputLabels, outputLabels: tool.outputLabels,
                // A tool contributes no DSP, so nothing here is a port in the
                // graph sense. Master's `input` still mixes, which is what a
                // patcher needs to know to grow slots on it.
                audioInputs: kind == master ? ["input"] : []
            )
        }
        if let kernel = kernelsByKind[kind] {
            return CatalogJacks(
                inputs: kernel.inputs, outputs: kernel.outputs,
                inputLabels: kernel.inputLabels, outputLabels: kernel.outputLabels,
                audioInputs: Set(kernel.inputs.filter { $0 == "input" || $0 == "sidechain" })
            )
        }
        return nil
    }

    private var master: String { io.master }

    /// Any palette kind's label, for a node title.
    public func label(_ kind: String) -> String {
        materialsByKind[kind]?.label ?? toolsByKind[kind]?.label ?? kernelsByKind[kind]?.label ?? kind
    }

    /// Kinds this build can actually compile and run.
    ///
    /// Derived by compiling every material once, not by carrying a list of
    /// exceptions. The two differ the day a gap is closed: a list still hides
    /// the kind it used to exclude, and asking the interpreter cannot be
    /// wrong. It also cannot go stale against a catalog regenerated from a
    /// newer palette.
    ///
    /// The whole set costs about 85 ms on a Mac and is computed once, so a
    /// caller that opens a palette should ask for it off the main thread and
    /// let the first answer arrive a moment later rather than blocking on it.
    public var runnableKinds: Set<String> {
        if let cached = runnableCache.value { return cached }
        var runnable = Set<String>()
        for material in materials where (try? CompiledVoice(document: material.graph)) != nil {
            runnable.insert(material.kind)
        }
        runnableCache.value = runnable
        return runnable
    }

    /// Whether a palette kind will run here. Host tools always will: they
    /// contribute no DSP of their own.
    public func canCompile(_ kind: String) -> Bool {
        if isHostTool(kind) { return true }
        guard materialsByKind[kind] != nil else { return false }
        return runnableKinds.contains(kind)
    }

    /// Why a kind cannot be placed, in words a palette can print, or nil when
    /// it can be.
    public func refusal(for kind: String) -> String? {
        if let kernel = kernelsByKind[kind] { return kernel.reason }
        if canCompile(kind) { return nil }
        if materialsByKind[kind] != nil {
            return "this build's interpreter does not implement every input this material uses"
        }
        return "nothing in the catalog resolves this kind"
    }

    private let runnableCache = RunnableCache()

    private final class RunnableCache: @unchecked Sendable {
        private let lock = NSLock()
        private var stored: Set<String>?
        var value: Set<String>? {
            get { lock.lock(); defer { lock.unlock() }; return stored }
            set { lock.lock(); stored = newValue; lock.unlock() }
        }
    }

    /// Categories in the order the palette shows them, taken from the entries
    /// rather than restated, so a new category cannot be invisible here.
    public var categories: [String] {
        var seen = Set<String>()
        var order = [String]()
        for category in tools.map(\.category) + materials.map(\.category) + kernels.map(\.category)
        where !seen.contains(category) {
            seen.insert(category)
            order.append(category)
        }
        return order
    }
}

/// What a patcher needs to draw one node's jacks.
///
/// `audioInputs` is the set that **mixes**: stacked cables into one of these
/// sum rather than replacing each other, which is why an editor grows slots
/// on them instead of letting the second cable evict the first.
public struct CatalogJacks: Sendable {
    public let inputs: [String]
    public let outputs: [String]
    public let inputLabels: [String]
    public let outputLabels: [String]
    public let audioInputs: Set<String>

    public func inputLabel(_ index: Int) -> String {
        index < inputLabels.count ? inputLabels[index] : (index < inputs.count ? inputs[index] : "")
    }

    public func outputLabel(_ index: Int) -> String {
        index < outputLabels.count ? outputLabels[index] : (index < outputs.count ? outputs[index] : "")
    }
}

/// The node kinds a patch document uses for host I/O. Generated alongside the
/// palette so the two editors cannot disagree about what `master` is called.
public struct PatchIoKinds: Codable, Sendable {
    public let master: String
    public let line: String
    public let keyboard: String
    public let transport: String
    public let midiIn: String
    public let midiOut: String

    public func contains(_ kind: String) -> Bool {
        kind == master || kind == line || kind == keyboard
            || kind == transport || kind == midiIn || kind == midiOut
    }
}

public struct CatalogToolEntry: Decodable, Sendable, Identifiable {
    public let kind: String
    public let label: String
    public let category: String
    public let inputs: [String]
    public let outputs: [String]
    /// How each jack is written on a node, generated by crate's own
    /// `formatJack`. The web editor says audio-or-control with the socket's
    /// shape; Flow draws its own ports, so here it is in the text.
    public let inputLabels: [String]
    public let outputLabels: [String]

    public var id: String { kind }
}

public struct CatalogKernelEntry: Decodable, Sendable, Identifiable {
    public let kind: String
    public let label: String
    public let category: String
    public let inputs: [String]
    public let outputs: [String]
    public let inputLabels: [String]
    public let outputLabels: [String]
    /// Why this build will not run it, in words a palette can print.
    public let reason: String

    public var id: String { kind }
}

public struct CatalogMaterialEntry: Decodable, Sendable, Identifiable {
    public let kind: String
    public let label: String
    public let category: String
    /// `analysis` or `looper`: kinds whose non-audio outlets are derived from
    /// their audio rather than being jacks in their own right.
    public let trait: String?
    public let cvPolarity: String
    public let polyphony: Int
    /// Live audio inlets. A cable into one of these mixes into a port; a
    /// cable into anything else maps onto a param.
    public let audioInputs: [String]
    public let automatable: [String]
    /// Declaration order of `params`. Load-bearing: flatten republishes in
    /// this order and assigns addresses in it, and a Swift dictionary does
    /// not keep the order the JSON had.
    public let paramOrder: [String]
    public let params: [String: CrateParamDescriptor]
    public let inputs: [String]
    public let outputs: [String]
    public let inputLabels: [String]
    public let outputLabels: [String]
    public let graph: ASLGraphDocument

    public var id: String { kind }
    public var isUnipolar: Bool { cvPolarity == "unipolar" }
    public var isAnalysis: Bool { trait == "analysis" }
    public var isLooper: Bool { trait == "looper" }

    public func isAudioInlet(_ name: String) -> Bool { audioInputs.contains(name) }
    public func param(_ name: String) -> CrateParamDescriptor? { params[name] }

    /// Every `param` name this material's graph reads, computed once when the
    /// catalog is decoded. See `MaterialCatalog.canReceiveCable`.
    public var paramsTheGraphReads: Set<String> {
        var names = Set<String>()
        var seen = Set<Int>()
        func walk(_ node: ASLNodeDocument) {
            guard seen.insert(node.id).inserted else { return }
            if node.kind == "param", case let .string(name)? = node.params["name"] {
                names.insert(name)
            }
            for (_, child) in node.inputs { walk(child) }
            for child in node.list ?? [] { walk(child) }
        }
        walk(graph.output)
        return names
    }

    /// Params in declaration order, skipping any the catalog lists in
    /// `paramOrder` but does not describe. That mismatch cannot happen in a
    /// file the emitter wrote, and silently publishing a param with no
    /// descriptor would be worse than leaving it out.
    public var orderedParams: [(name: String, descriptor: CrateParamDescriptor)] {
        paramOrder.compactMap { name in params[name].map { (name, $0) } }
    }
}
