// GENERATED by tools/gen_params.py — do not edit by hand.
// Source of truth: the AUv3 Parameters.swift. Re-run the script to sync.
#pragma once
#include <cstdint>

enum class HCUnit { Generic, Indexed, Boolean, Seconds, Hertz, Milliseconds, LinearGain, SemiTones, Decibels };

struct HCParamSpec {
    uint32_t    id;          // == AU parameter address
    const char* identifier;
    const char* title;
    const char* groupId;
    const char* groupName;
    HCUnit      unit;
    float       minValue;
    float       maxValue;
    float       defaultValue;
};

static constexpr int kHCParamCount = 79;

static constexpr HCParamSpec kHCParams[kHCParamCount] = {
    { 0, "inputGain", "Input Gain", "global", "Global", HCUnit::LinearGain, 0.0f, 4.0f, 1.0f },
    { 1, "outputGain", "Output Gain", "global", "Global", HCUnit::LinearGain, 0.0f, 4.0f, 1.0f },
    { 2, "driveAmount", "Drive", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 3, "dryLevel", "Dry Level", "global", "Global", HCUnit::Generic, 0.0f, 1.0f, 1.0f },
    { 10, "captureMode", "Capture Mode", "capture", "Capture", HCUnit::Indexed, 0.0f, 1.0f, 0.0f },
    { 11, "catchTrigger", "Catch", "capture", "Capture", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 12, "freezeHold", "Freeze", "capture", "Capture", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 13, "loopLength", "Loop Length", "capture", "Capture", HCUnit::Seconds, 0.25f, 5.0f, 2.0f },
    { 14, "loopSync", "Loop Sync", "capture", "Capture", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 15, "loopDivision", "Loop Division", "capture", "Capture", HCUnit::Indexed, 0.0f, 4.0f, 2.0f },
    { 16, "loopOverdub", "Overdub", "capture", "Capture", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 17, "loopFade", "Loop Fade", "capture", "Capture", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 18, "captureSource", "Capture Source", "capture", "Capture", HCUnit::Indexed, 0.0f, 2.0f, 0.0f },
    { 30, "grainMix", "Grain Mix", "grain", "Grain", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 31, "grainSize", "Grain Size", "grain", "Grain", HCUnit::Milliseconds, 20.0f, 500.0f, 120.0f },
    { 32, "grainDensity", "Grain Density", "grain", "Grain", HCUnit::Hertz, 2.0f, 80.0f, 18.0f },
    { 33, "grainSpray", "Spray", "grain", "Grain", HCUnit::Generic, 0.0f, 1.0f, 0.25f },
    { 34, "grainPitch", "Grain Pitch", "grain", "Grain", HCUnit::Generic, -24.0f, 24.0f, 0.0f },
    { 35, "grainPitchQuant", "Pitch Quantize", "grain", "Grain", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 36, "grainPitchRand", "Pitch Random", "grain", "Grain", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 37, "grainReverse", "Reverse", "grain", "Grain", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 38, "grainSpread", "Spread", "grain", "Grain", HCUnit::Generic, 0.0f, 1.0f, 0.6f },
    { 39, "grainShape", "Grain Shape", "grain", "Grain", HCUnit::Indexed, 0.0f, 3.0f, 0.0f },
    { 40, "grainFeedback", "Grain Feedback", "grain", "Grain", HCUnit::Generic, 0.0f, 0.9f, 0.0f },
    { 41, "grainScan", "Scan", "grain", "Grain", HCUnit::Generic, -2.0f, 2.0f, 1.0f },
    { 42, "grainClock", "Clock", "grain", "Grain", HCUnit::Indexed, 0.0f, 3.0f, 0.0f },
    { 43, "crossTarget", "Cross Target", "grain", "Grain", HCUnit::Indexed, 0.0f, 4.0f, 0.0f },
    { 44, "crossAmount", "Cross Amount", "grain", "Grain", HCUnit::Generic, 0.0f, 1.0f, 0.5f },
    { 45, "grainTone", "Grain Tone", "grain", "Grain", HCUnit::Generic, 0.0f, 1.0f, 0.5f },
    { 46, "midiMode", "MIDI Mode", "grain", "Grain", HCUnit::Indexed, 0.0f, 2.0f, 0.0f },
    { 47, "midiRoot", "MIDI Root", "grain", "Grain", HCUnit::Generic, 0.0f, 127.0f, 60.0f },
    { 48, "midiAttack", "MIDI Attack", "grain", "Grain", HCUnit::Milliseconds, 1.0f, 2000.0f, 5.0f },
    { 49, "midiRelease", "MIDI Decay", "grain", "Grain", HCUnit::Milliseconds, 5.0f, 5000.0f, 250.0f },
    { 50, "delayTime", "Delay Time", "delay", "Delay", HCUnit::Milliseconds, 20.0f, 2000.0f, 350.0f },
    { 51, "delayFeedback", "Delay Feedback", "delay", "Delay", HCUnit::Generic, 0.0f, 1.0f, 0.35f },
    { 52, "delayTone", "Delay Tone", "delay", "Delay", HCUnit::Generic, 0.0f, 1.0f, 0.7f },
    { 53, "delayLevel", "Delay Level", "delay", "Delay", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 54, "delaySync", "Delay Sync", "delay", "Delay", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 55, "delayDivision", "Delay Division", "delay", "Delay", HCUnit::Indexed, 0.0f, 6.0f, 1.0f },
    { 56, "delayPingPong", "Delay Ping-Pong", "delay", "Delay", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 57, "delayTape", "Delay Tape", "delay", "Delay", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 58, "delayDuck", "Delay Duck", "delay", "Delay", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 59, "delaySend", "Delay Send", "delay", "Delay", HCUnit::Indexed, 0.0f, 2.0f, 0.0f },
    { 60, "delayRoute", "Delay Route", "delay", "Delay", HCUnit::Indexed, 0.0f, 3.0f, 0.0f },
    { 61, "delayOscillate", "Delay Oscillate", "delay", "Delay", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 70, "reverbDecay", "Reverb Decay", "reverb", "Reverb", HCUnit::Generic, 0.0f, 1.0f, 0.5f },
    { 71, "reverbBlend", "Reverb Wet", "reverb", "Reverb", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 72, "reverbSize", "Reverb Size", "reverb", "Reverb", HCUnit::Generic, 0.5f, 2.0f, 1.0f },
    { 73, "reverbPreDelay", "Reverb PreDelay", "reverb", "Reverb", HCUnit::Milliseconds, 0.0f, 100.0f, 10.0f },
    { 74, "reverbTone", "Reverb Tone", "reverb", "Reverb", HCUnit::Generic, 0.0f, 1.0f, 0.7f },
    { 75, "reverbDryFeed", "Reverb Dry Feed", "reverb", "Reverb", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 80, "washAmount", "Wash", "wash", "Wash & Glue", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 81, "washWarble", "Wash Warble", "wash", "Wash & Glue", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 82, "washMode", "Wash Mode", "wash", "Wash & Glue", HCUnit::Indexed, 0.0f, 2.0f, 0.0f },
    { 83, "glueAmount", "Glue", "wash", "Wash & Glue", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 90, "catchCC", "Catch CC", "cc", "MIDI CC", HCUnit::Generic, 0.0f, 127.0f, 24.0f },
    { 91, "freezeCC", "Freeze CC", "cc", "MIDI CC", HCUnit::Generic, 0.0f, 127.0f, 25.0f },
    { 92, "oscillateCC", "Oscillate CC", "cc", "MIDI CC", HCUnit::Generic, 0.0f, 127.0f, 27.0f },
    { 100, "resMix", "Resonator Mix", "resonator", "Resonator", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 101, "resQ", "Resonator Q", "resonator", "Resonator", HCUnit::Generic, 0.0f, 1.0f, 0.5f },
    { 102, "resRotate", "Resonator Rotate", "resonator", "Resonator", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 103, "resSpread", "Resonator Spread", "resonator", "Resonator", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 104, "keyMask", "Key Mask", "resonator", "Resonator", HCUnit::Generic, 1.0f, 4095.0f, 2741.0f },
    { 105, "resRoot", "Resonator Root", "resonator", "Resonator", HCUnit::Generic, 24.0f, 72.0f, 40.0f },
    { 106, "resMorph", "Resonator Morph", "resonator", "Resonator", HCUnit::Generic, 0.0f, 1.0f, 0.3f },
    { 107, "resBandMask", "Resonator Bands", "resonator", "Resonator", HCUnit::Generic, 1.0f, 63.0f, 63.0f },
    { 108, "resSend", "Resonator Send", "resonator", "Resonator", HCUnit::Indexed, 0.0f, 2.0f, 2.0f },
    { 110, "resLfoTarget", "Reso LFO Target", "resolfo", "Reso LFO", HCUnit::Indexed, 0.0f, 6.0f, 0.0f },
    { 111, "resLfoRate", "Reso LFO Rate", "resolfo", "Reso LFO", HCUnit::Hertz, 0.05f, 8.0f, 1.0f },
    { 112, "resLfoSync", "Reso LFO Sync", "resolfo", "Reso LFO", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 113, "resLfoDivision", "Reso LFO Division", "resolfo", "Reso LFO", HCUnit::Indexed, 0.0f, 6.0f, 1.0f },
    { 114, "resLfoShape", "Reso LFO Shape", "resolfo", "Reso LFO", HCUnit::Indexed, 0.0f, 5.0f, 0.0f },
    { 115, "resLfoDepth", "Reso LFO Depth", "resolfo", "Reso LFO", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
    { 120, "grainLfoTarget", "Grain LFO Target", "grainlfo", "Grain LFO", HCUnit::Indexed, 0.0f, 7.0f, 0.0f },
    { 121, "grainLfoRate", "Grain LFO Rate", "grainlfo", "Grain LFO", HCUnit::Hertz, 0.05f, 8.0f, 1.0f },
    { 122, "grainLfoSync", "Grain LFO Sync", "grainlfo", "Grain LFO", HCUnit::Boolean, 0.0f, 1.0f, 0.0f },
    { 123, "grainLfoDivision", "Grain LFO Division", "grainlfo", "Grain LFO", HCUnit::Indexed, 0.0f, 6.0f, 1.0f },
    { 124, "grainLfoShape", "Grain LFO Shape", "grainlfo", "Grain LFO", HCUnit::Indexed, 0.0f, 5.0f, 0.0f },
    { 125, "grainLfoDepth", "Grain LFO Depth", "grainlfo", "Grain LFO", HCUnit::Generic, 0.0f, 1.0f, 0.0f },
};
