export { Time, time, type TimeContext } from './Time';
export { TempoMap, type TempoChange, type TempoCurve } from './TempoMap';
export { AudioScene, type AudioSceneOptions } from './AudioScene';
export { Transport, type TransportState, type TransportHost, type PlaybackOrigin } from './Transport';
export {
  planScenePlayback,
  type PlaybackPlan,
  type PlannedClipJob,
  type PlannedMidiJob,
  type PlannedMidiCcJob,
  type PlanScenePlaybackInput,
} from './playback/plan';
export { ScenePlayback, type PlaybackStart, type TrackFader } from './playback/ScenePlayback';
export {
  prepareLiveVoices,
  disposeLiveVoices,
  type LiveVoiceRenderer,
  type LiveWasmBinaries,
  type LiveTrackVoices,
  type LiveSceneVoices,
} from './playback/liveVoices';
export {
  HostedAutomationBridge,
  type ClipGainTarget,
  type HostedAutomationBinding,
} from './playback/hostedAutomation';
export {
  InputMonitor,
  type LiveInputNode,
  type MonitorMode,
  type MonitorTrackConfig,
  type MonitorStart,
} from './playback/InputMonitor';
export { MidiPlayback, type MidiVoiceTarget, type MidiPlaybackStart } from './playback/MidiPlayback';
export { SceneNotStartedError, MaterialNotBoundError } from './errors';
export {
  HookSystem,
  createHookSystem,
  hooks,
  CRATE_SLOTS,
  createReactHooks,
  type HookContext,
  type SlotComponent,
  type SlotComponentConfig,
  type CrateSlotName,
} from './hooks';
export type { AudioContextLike } from './AudioContextLike';
export {
  WebAudioRenderer,
  type VoiceHandle,
  type WebAudioRendererOptions,
  type AnalysisMessage,
} from './renderers/WebAudioRenderer';
export { OfflineRenderer, type OfflineRenderOptions, type OfflineRenderResult } from './renderers/OfflineRenderer';
export { AudioNode3, type AudioNode3Options } from './graph/AudioNode3';
export { Track, type TrackOptions, type ScheduledClip, type ScheduledMidiClip } from './graph/Track';
export { Bus, type BusOptions } from './graph/Bus';
export { Clip, type ClipOptions, type AudioBufferLike } from './graph/Clip';
export {
  MidiClip,
  expandMidiNotes,
  midiVelocity,
  midiCcValue,
  type MidiNote,
  type MidiCcEvent,
  type MidiCcPoint,
  type MidiCcLane,
  type MidiClipOptions,
} from './graph/MidiClip';
export {
  clipPlaybackWindows,
  clipTimelineDurationSec,
  resolveTrimEndSec,
  warpSegmentsFromMs,
  type SampleRegion,
  type WarpSegment,
  type ClipPlaybackWindow,
} from './clip/region';
export {
  fadeShape,
  clipGainLinear,
  applyClipGainAndFades,
  fadeCurveName,
  type FadeCurve,
  type ApplyClipFadesOptions,
} from './clip/fades';
export {
  projectClipCrossfades,
  CROSSFADE_ADJACENCY_EPS_SEC,
  type CrossfadeClipDraft,
} from './clip/crossfade';
export {
  pdcStartDelaySec,
  pdcAudibleOriginSec,
  chainLatencySamples,
  PDC_SCHEDULE_AHEAD_SEC,
} from './host/pdc';
export {
  Material,
  MaterialChain,
  type MaterialOptions,
  type MaterialGraphBuilder,
  type MaterialGraphContext,
  type VoiceStealingPolicy,
  type VoiceSnapshot,
  type AudioSourceRef,
  type CvPolarity,
} from './graph/Material';
export type {
  TextAssetData,
  AudioAssetData,
  IrAssetData,
  AssetRequest,
  AssetDecodeKind,
} from './graph/assets';
export { MaterialRegistry, materialRegistry, registerMaterial } from './registry';
export type { MaterialPlugin, HostPluginIdentity } from './registry';
export { bakeTrackInserts, type BakeTrackInsertsOptions } from './playback/bakeInserts';
export {
  BlockRenderer,
  type BlockRendererOptions,
  type RenderedBlock,
} from './renderers/BlockRenderer';
export { defineCrateVoiceProcessor } from './renderers/worklet/defineVoiceProcessor';
/**
 * Audiocrate's own worklet, and the URLs it can be delivered by.
 *
 * `WebAudioRenderer` uses these for you. They are public because a host
 * sometimes needs the module before crate does: loading it into an
 * `AudioContext` it owns, warming it during a loading screen so the first
 * note is not the thing that pays for `addModule`, or reporting which URL
 * scheme a given browser accepted.
 */
export { crateWorkletUrls, CRATE_WORKLET_SOURCE } from './renderers/worklet/workletUrls';
export type {
  KernelProcessor,
  KernelBindings,
  KernelFactory,
  KernelFactoryMap,
  KernelBinaryMap,
} from './renderers/kernel';
export { VoicePool, type VoiceBackend } from './voices/VoicePool';
export { allocateSlot } from './voices/allocate';
export { Easing, type EasingFn, type EasingName } from './automation/Easing';
export { AutomationLane, type AutomationLaneOptions, type AutomationRange } from './automation/AutomationLane';
export { evaluateNodeAutomation } from './automation/evaluate';
export {
  evaluateHostedAutomation,
  clipLevelValue,
  HOSTED_MASTER_TRACK_INDEX,
  type HostedAutomationTrack,
  type HostedAutomationClip,
  type HostedAutomationLane,
  type HostedAutomationWrite,
} from './automation/hosted';
export {
  param,
  paramNameForAddress,
  quantizeParam,
  normalizeParam,
  denormalizeParam,
  formatParam,
  enumValue,
  type ParamDescriptor,
  type ParamDescriptorBase,
  type ParamCurve,
  type RangeParamDescriptor,
  type RangeParamOptions,
  type SteppedParamDescriptor,
  type SteppedParamOptions,
  type EnumParamDescriptor,
  type EnumParamOptions,
  type ToggleParamDescriptor,
  type ToggleParamOptions,
} from './graph/param';
export {
  describeMaterial,
  describeControl,
  humanizeParamName,
  type InspectorModel,
  type InspectorControl,
  type ControlKind,
} from './graph/inspector';
export {
  filter,
  kernel,
  osc,
  lfo,
  mix,
  env,
  uniform,
  noise,
  delay,
  clip,
  dcBlock,
  envFollow,
  bitcrush,
  downsample,
  rectify,
  slew,
  sampleHold,
  compare,
  compressor,
  clock,
  clockDivide,
  clockMultiply,
  logic,
  flipFlop,
  quantize,
  euclidean,
  random,
  trigger,
  pulse,
  sequencer,
  impulse,
  expander,
  transient,
  reverse,
  looper,
  createLooperBox,
  LOOPER_FIELDS,
  select,
  waveshape,
  rms,
  peak,
  onset,
  pitch,
  wavetable,
  samplePlay,
  grain,
  pitchShift,
  panLaw,
  audio,
  MAIN_PORT,
} from './asl/builders';
export { audioPortNames, auxAudioPorts } from './asl/ports';
/**
 * The graph itself, as a type and as a builder.
 *
 * `Material.graph` is public and is an `ASLGraphDescriptor`, so a consumer
 * that could not name the type could not write a function taking one: a host
 * adapter wanting to accept "a Material or a bare graph" had to describe the
 * shape structurally and hope. `ASL.node` is the matching builder for a graph
 * authored without a Material around it.
 */
export { ASL } from './asl/graph';
export type { ASLGraphDescriptor } from './asl/graph';
export type { ASLNode, NodeKind, TransportField, LooperBox } from './asl/types';
export type { LooperField } from './asl/builders';
export { ALL_NODE_KINDS, ALL_TRANSPORT_FIELDS } from './asl/types';
export {
  transport,
  transportAt,
  advanceTransport,
  divisionBeats,
  normalizeBeatUnit,
  signatureBeatBeats,
  barBeats,
  SYNC_DIVISIONS,
  SYNC_DIVISION_NAMES,
  SYNC_DIVISION_BEATS,
  COMMON_DIVISION_NAMES,
  COMMON_DIVISION_BEATS,
  DEFAULT_TRANSPORT,
  DEFAULT_TRANSPORT_ANCHOR,
  type SyncDivision,
  type TransportSnapshot,
  type TransportAnchor,
  type TransportSegment,
} from './asl/transportNodes';
export { tap, DEFAULT_CAPTURE_WINDOW } from './asl/analysis';
export type { MeterReading, AnalysisFrame } from './asl/analysis';
export {
  synthVoiceMaterial,
  parametricEqMaterial,
  EQ_BAND_TYPES,
  gainMaterial,
  spatialSourceMaterial,
  spatialMasterMaterial,
  SPATIAL_SOURCE_KIND,
  SPATIAL_MASTER_KIND,
  SPATIAL_DECODE_MODES,
  invertMaterial,
  lowpassMaterial,
  highpassMaterial,
  bandpassMaterial,
  notchMaterial,
  lowShelfMaterial,
  highShelfMaterial,
  allpassMaterial,
  onePoleLowpassMaterial,
  onePoleHighpassMaterial,
  svfLowpassMaterial,
  svfHighpassMaterial,
  svfBandpassMaterial,
  ladderMaterial,
  combMaterial,
  slopeLowpass12Material,
  slopeLowpass24Material,
  slopeHighpass12Material,
  oscillatorMaterial,
  OSC_WAVE_NAMES,
  NOISE_COLOR_NAMES,
  toneMaterial,
  noiseMaterial,
  impulseMaterial,
  wavetableMaterial,
  createWavetableMaterial,
  setWavetable,
  setWavetableAsset,
  clearWavetableAsset,
  wavetableAsset,
  WAVETABLE_ASSET,
  wavetableBank,
  WAVETABLE_FRAME_SIZE,
  samplePlayerMaterial,
  createSamplePlayerMaterial,
  setSampleAsset,
  clearSampleAsset,
  sampleAsset,
  SAMPLE_ASSET,
  sineTable,
  softClipMaterial,
  hardClipMaterial,
  bitcrushMaterial,
  downsampleMaterial,
  fullRectifyMaterial,
  halfRectifyMaterial,
  slewMaterial,
  sampleHoldMaterial,
  compareGreaterMaterial,
  compareLessMaterial,
  clockMaterial,
  clockDivideMaterial,
  clockMultiplyMaterial,
  logicAndMaterial,
  logicOrMaterial,
  logicXorMaterial,
  logicNotMaterial,
  flipFlopMaterial,
  quantizeMaterial,
  euclideanMaterial,
  randomSteppedMaterial,
  randomSmoothMaterial,
  triggerMaterial,
  pulseMaterial,
  sequencerMaterial,
  adsrMaterial,
  lfoMaterial,
  dahdsrMaterial,
  offsetMaterial,
  controlMaterial,
  breakpointEnvelopeMaterial,
  compressorMaterial,
  limiterMaterial,
  gateMaterial,
  expanderMaterial,
  transientMaterial,
  selectMaterial,
  panLeftMaterial,
  panRightMaterial,
  mixMaterial,
  reverseMaterial,
  looperMaterial,
  LOOPER_QUANTIZE_NAMES,
  LOOPER_LENGTH_PRESETS,
  LOOPER_OUTPUTS,
  LOOPER_START_TAP,
  LOOPER_END_TAP,
  isLooperKind,
  isLooperPulseOutput,
  pitchShiftMaterial,
  grainMaterial,
  createGrainMaterial,
  setGrainAsset,
  rmsMaterial,
  peakMaterial,
  onsetMaterial,
  syncedDelayMaterial,
  syncedRampMaterial,
  syncedClockMaterial,
  syncedTremoloMaterial,
  syncedMaterials,
  transportMaterial,
  TRANSPORT_KIND,
  TRANSPORT_OUTPUTS,
  TRANSPORT_ABSOLUTE_OUTPUTS,
  TIME_SIG_PRESETS,
  isTransportKind,
  isTransportOutput,
  isTransportAbsoluteOutput,
  resolvedTransport,
  transportFromMaterial,
  applyTransportToMaterial,
  waveshapeMaterial,
  WAVESHAPE_CURVES,
  bypassMaterial,
  dcBlockerMaterial,
  delayMaterial,
  reverbMaterial,
  envelopeFollowerMaterial,
  ringModMaterial,
  irMaterial,
  createIrMaterial,
  setIrAsset,
  irAsset,
  irLatencySamples,
  IR_ASSET,
  IR_ASSET_REF,
  irPlugin,
  setLiveIrPartitionSize,
  monoSumMaterial,
  monoLeftMaterial,
  monoRightMaterial,
  channelSwapMaterial,
  stereoWidthMaterial,
  midSideEncodeMaterial,
  midSideDecodeMaterial,
  balanceMaterial,
  stereoPanMaterial,
  autoPanMaterial,
  haasMaterial,
  stereoMergeMaterial,
  createStereoMergeMaterial,
  stereoMaterials,
  sidechainCompressorMaterial,
  duckerMaterial,
  sidechainGateMaterial,
  audioMultiplyMaterial,
  audioMixMaterial,
  crossfadeMaterial,
  inputSelectMaterial,
  sidechainMaterials,
  sidechainMaterialFactories,
  createSidechainCompressorMaterial,
  createDuckerMaterial,
  createSidechainGateMaterial,
  createAudioMultiplyMaterial,
  createAudioMixMaterial,
  createCrossfadeMaterial,
  createInputSelectMaterial,
  meterMaterial,
  scopeMaterial,
  analyzerMaterial,
  tunerMaterial,
  createMeterMaterial,
  createScopeMaterial,
  createAnalyzerMaterial,
  createTunerMaterial,
  METER_TAP,
  SCOPE_TAP,
  METER_OUTPUTS,
  SCOPE_OUTPUTS,
  TUNER_OUTPUTS,
  ANALYZER_OUTPUTS,
  isAnalysisKind,
  analysisOutputs,
  isAnalysisAbsoluteOutput,
  registerCoreMaterials,
  corePlugins,
} from './materials';
export type { TransportOutput, TransportAbsoluteOutput, MaterialTransport, AnalysisKind } from './materials';
export { AudioLoader, decodeWav, decodeCaf, decodeAudioFile } from './loaders/AudioLoader';
export { IRLoader, decodeImpulseResponse } from './loaders/IRLoader';
export { IR_KERNEL_SLOT, irKernelFactory, createIrKernel } from './renderers/kernels/irKernel';
export {
  WASM_KERNEL_SLOT,
  CRATE_KERNEL_ABI_VERSION,
  wasmKernelFactory,
  isWasmKernelPayload,
  type WasmKernelDescriptor,
  type WasmKernelPayload,
} from './renderers/kernels/wasmKernel';
export {
  fetchKernelBinary,
  clearKernelBinaryCache,
  type FetchKernelBinaryOptions,
} from './renderers/kernels/kernelBinary';
export {
  SceneSync,
  SessionClock,
  SnapshotBuffer,
  StateCodec,
  LoopbackHub,
  LoopbackTransport,
  P2pcfTransport,
  p2pcfPeerId,
  cratePeerCodec,
  CRATE_PEER_FIELDS,
  CRATE_PROTOCOL_VERSION,
  CRATE_CHANNEL_PREFIX,
  MESSAGE,
  encodeEdit,
  decodeEdit,
  compareEdits,
  sessionHost,
  peerHash,
  quantize16,
  dequantize16,
  lerp,
  blendRecords,
  type CollabTransport,
  type CollabPeer,
  type SceneSyncOptions,
  type RemotePeerState,
  type SceneEdit,
  type EditConflict,
  type EditValue,
  attachAudioScene,
  applySceneEdit,
  type SessionClockOptions,
  type SessionParticipant,
  type ClockSample,
  type P2pcfLike,
  type P2pcfPeerLike,
  type P2pcfTransportOptions,
  type SnapshotBufferOptions,
  type Snapshot,
  type StateField,
  type FieldEncoding,
  type DecodedState,
  type MessageType,
} from './collab';
export { IR_PARTITION_SIZE, PartitionedConvolver, convolveDirect } from './dsp/convolver';
export { fftRadix2, fftMagnitude } from './dsp/fft';
export { yinPitch } from './dsp/yin';
export { momentaryLufs } from './dsp/lufs';
export {
  MidiLoader,
  decodeMidi,
  encodeMidi,
  midiFileToClips,
  createWebMidiBridge,
  type MidiFile,
  type MidiFileTrack,
  type WebMidiBridge,
  type WebMidiAccessLike,
  type WebMidiInputLike,
  type WebMidiTarget,
} from './loaders/MidiLoader';
export {
  MIDI_IN_KIND,
  MIDI_OUT_KIND,
  MIDI_IN_OUTPUTS,
  MIDI_OUT_INPUTS,
  MIDI_MESSAGE_NAMES,
  A4_MIDI,
  DEFAULT_MIDI_IN_FIELDS,
  DEFAULT_MIDI_OUT_FIELDS,
  isMidiInKind,
  isMidiOutKind,
  isMidiIoKind,
  isMidiInOutput,
  isMidiOutInput,
  midiInletValue,
  midiInletGate,
  voltsFromMidi,
  midiFromVolts,
  clampMidi,
  midi7,
  midiInputChannel,
  midiOutputChannel,
  midiMessageIndex,
  readMidiIoFields,
  createMidiOutputState,
  resolveMidiPitch,
  stepMidiOutput,
  encodeMidiVoiceEvent,
  parseMidiBytes,
  MidiInputMonitor,
  type MidiInOutput,
  type MidiOutInput,
  type MidiMessageName,
  type MidiPortInfo,
  type MidiIoFields,
  type MidiVoiceEvent,
  type MidiOutputSample,
  type MidiOutputCables,
  type MidiOutputState,
  type MidiInputEvent,
  type MidiInputSnapshot,
} from './midi/midiIo';
export {
  SCENE_PLAN_VERSION,
  planTempoMap,
  planTimeContext,
  planClipDurationSec,
  scheduleClip,
  schedulePlan,
  type ScenePlan,
  type ScenePlanTransport,
  type ScenePlanTrack,
  type ScenePlanClip,
  type ScenePlanLane,
  type PlanClipSchedule,
  type PlanTrackSchedule,
  type PlanSchedule,
} from './session/ScenePlan';
export {
  generateSource,
  sampleSourceAt,
  renderPlan,
  sourceDurationSec,
  type PlanSourceSpec,
  type PlanRenderOptions,
} from './session/planRender';
export {
  timeStretch,
  bakeClipStretch,
  clampStretchRatio,
  stretchedLength,
  MIN_STRETCH_RATIO,
  MAX_STRETCH_RATIO,
  STRETCH_FRAME,
  type TimeStretchOptions,
} from './dsp/timeStretch';
export {
  buildScenePlan,
  type PlanBuildInput,
  type PlanBuildClip,
  type PlanBuildTrack,
} from './session/buildScenePlan';
export {
  MIDI_TRIG_SECONDS,
  emptyMidiCables,
  emptyMidiSample,
  midiInOutlets,
  midiOutSample,
  type MidiInletReading,
} from './midi/midiHostIo';
export {
  listMidiPorts,
  findMidiInput,
  findMidiOutput,
  requestMidiAccess,
  midiPortValues,
  listenMidiInput,
  type WebMidiOutputLike,
  type WebMidiInputPortLike,
  type WebMidiAccessPorts,
} from './midi/webMidi';
export {
  ProjectLoader,
  parseProject,
  loadProjectScene,
  resolveAudioPath,
  readProjectTempoMap,
  writeProjectTempoMap,
  type ProjectTempoChangeData,
  type ProjectTempoMapResult,
  type ParsedProject,
  type ProjectFileData,
  type ProjectTrackData,
  type ProjectClipData,
  type ProjectMidiTrackData,
  type ProjectMidiClipData,
  type ProjectMidiNoteData,
  type ProjectMasterData,
  type ProjectManifestData,
  type LoadProjectSceneOptions,
} from './loaders/ProjectLoader';
export {
  ProjectExporter,
  exportProject,
  PROJECT_ARCHIVE_KIND,
  PROJECT_ARCHIVE_FORMAT_VERSION,
  type ExportProjectOptions,
  type ExportProjectResult,
} from './loaders/ProjectExporter';
export {
  listPluginSlots,
  resolveProjectAssetPath,
  decodeAddressedParams,
  asPresetNumber,
  asPresetFilename,
  AU_TYPE_EFFECT,
  AU_TYPE_MUSIC_EFFECT,
  AU_TYPE_INSTRUMENT,
  type PluginSlot,
  type AUv3PluginDescriptor,
} from './host/pluginSlots';
export { decodePresetBlob, decodeKeyedArchive } from './loaders/decodeKeyedArchive';
export {
  MemoryAudioStorage,
  getAudioStorage,
  setAudioStorage,
  resetAudioStorage,
  isMemoryAudioStorage,
  type AudioStorage,
  type AudioStorageRef,
  type AudioStoragePutOptions,
} from './storage/AudioStorage';
export {
  ChunkedHttpAudioStorage,
  CHUNKED_HTTP_CHUNK_SIZE,
  type ChunkedHttpAudioStorageOptions,
} from './storage/ChunkedHttpAudioStorage';
export { mapPluginSlot, type MappedPluginSlot } from './host/mapPluginSlot';
export {
  probeAudioCapabilities,
  crateFeatureSupport,
  describeCrateSupport,
  type AudioCapabilities,
  type CrateFeatureSupport,
} from './host/audioCapabilities';
export {
  HOST_LOCAL_NODE_KEYS,
  isHostLocalNodeKey,
  omitHostLocalNodeData,
  overlayHostLocalNodeData,
  stripHostLocalPatch,
  restoreHostLocalPatch,
  type HostLocalNodeKey,
  type HostLocalPatchNode,
  type HostLocalPatch,
} from './host/hostLocal';
export {
  flattenPatch,
  detectPatchRole,
  DEFAULT_PATCH_IO,
  type PatchDocument,
  type PatchDocumentNode,
  type PatchDocumentConnection,
  type PatchIoKinds,
  type FlattenPatchOptions,
} from './patcher/flattenPatch';
export {
  CRATE_PLUGIN_KIND,
  CRATE_PLUGIN_VERSION,
  USER_PLUGIN_MANUFACTURER,
  pluginSubtypeFromId,
  isCratePluginDocument,
  parseCratePlugin,
  stringifyCratePlugin,
  cratePluginDocument,
  pluginFromDocument,
  type CratePluginDocument,
  type CratePluginDocumentOptions,
  type CratePluginPreset,
  type PluginFromDocumentOptions,
} from './patcher/cratePlugin';
export {
  serializeGraph,
  serializeNode,
  compileMaterial,
  compileCratePlugin,
  type SerializedGraph,
  type SerializedASLNode,
  type CompiledMaterialDocument,
  type CompileCratePluginOptions,
} from './patcher/compiledPlugin';
export {
  Vec3,
  NAMED_POSITIONS,
  SPATIAL_POSITION_NAMES,
  namedPositionVec,
  isNamedSpatialPosition,
  sphericalToCartesian,
  cartesianToSpherical,
  FOA_W,
  foaGainsFromPoint,
  foaGainsFromDirection,
  foaGainsFromSpherical,
  stereoPanFromY,
  recoverYFromRMS,
  closestNamedPositionByY,
  DISTANCE_MODELS,
  distanceAttenuation,
  spatialUpdateHz,
  SPATIAL_SLOT_INDEX,
  parseSpatialMeta,
  buildSpatialMeta,
  SpatialListener,
  SpatialSource,
  SceneSpatial,
  encodeAmbisonics,
  SpatialBus,
  HeadTracker,
  availableHeadTrackerSources,
  poseFromDeviceOrientation,
  poseFromDrag,
  foaRotationMatrix,
  rotateFoaGains,
  decodeFoaToStereo,
  type HeadTrackerSource,
  type HeadPose,
  defineCrateFoaEncoder,
  FOA_ENCODER_PROCESSOR,
  FOA_CHANNELS,
  type SpatialDecodeMode,
  type SpatialBusOptions,
  type NamedSpatialPosition,
  type SpatialPositionName,
  type SphericalPos,
  type FOAGains,
  type SpatialMetaEntry,
  type SpatialSourceOptions,
} from './spatial';

/**
 * Standalone: nothing here touches a scene, a context or the
 * audio thread, so it is usable by someone who never creates an `AudioScene`.
 * Also reachable as `audiocrate/theory`.
 */
export * from './theory';
