/**
 * Is the fixture on disk still a description of this code?
 *
 * `kindCoverage.test.ts` closes uncovered node kinds. This file closes a
 * stale fixture: a change to a node's semantics is caught the moment the
 * fixture is regenerated, and not before. The fixture is generated by a
 * script; this test fails if the file on disk no longer matches what the
 * script would write.
 *
 * Without it: a filter changes, the JavaScript golden-audio snapshot is
 * updated, the fixture is not regenerated, and the Swift suite reports
 * agreement against the filter as it used to be.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import {
  CONFORMANCE_FIXTURE_VERSION,
  buildConformanceFixture,
  fixtureStamp,
  type ConformanceFixture,
} from '../../src/asl/conformanceFixture';

const FIXTURE_PATH = fileURLToPath(new URL('../../fixtures/asl-conformance.json', import.meta.url));

const REGENERATE = 'npm run fixtures:asl (from web-version/)';

function loadFixture(): ConformanceFixture {
  return JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as ConformanceFixture;
}

describe('conformance fixture', () => {
  const onDisk = loadFixture();
  const rebuilt = buildConformanceFixture();

  it('is not stale', () => {
    expect(
      onDisk.stamp,
      `fixtures/asl-conformance.json no longer describes this code, so the ` +
        `Swift conformance suite is being held to an older version of the ` +
        `interpreter and will pass regardless. Regenerate it: ${REGENERATE}`,
    ).toBe(rebuilt.stamp);
  });

  it('names the cases that changed, when it is stale', () => {
    // A stamp mismatch is one bit of information and the next question is
    // always "which case". Answering it here means a failure explains itself
    // instead of sending somebody to diff two megabytes of floats.
    const before = new Map(onDisk.cases.map((entry) => [entry.name, entry]));
    const after = new Map(rebuilt.cases.map((entry) => [entry.name, entry]));

    const added = [...after.keys()].filter((name) => !before.has(name));
    const removed = [...before.keys()].filter((name) => !after.has(name));
    const changed = [...after.keys()].filter((name) => {
      const old = before.get(name);
      if (!old) return false;
      return JSON.stringify(old) !== JSON.stringify(after.get(name));
    });

    expect({ added, removed, changed }).toEqual({ added: [], removed: [], changed: [] });
  });

  it('is self-consistent, so a hand-edited fixture is refused', () => {
    // The one file in the project where editing the evidence looks exactly
    // like fixing the bug.
    expect(fixtureStamp(onDisk)).toBe(onDisk.stamp);
  });

  it('is a format this build understands', () => {
    expect(onDisk.version).toBe(CONFORMANCE_FIXTURE_VERSION);
  });

  it('states the whole node vocabulary, not only the covered part', () => {
    // What the Swift side checks its own enum against. If this drifted from
    // ALL_NODE_KINDS the cross-language parity check would be comparing Swift
    // to a stale list and calling it agreement.
    expect(onDisk.kinds).toEqual(rebuilt.kinds);
    expect(onDisk.transportFields).toEqual(rebuilt.transportFields);
    expect(onDisk.exemptKinds).toEqual(rebuilt.exemptKinds);
  });

  it('carries a right channel for every graph that has one', () => {
    // The fixture used to record channel 0 and nothing else, which is the
    // exact blind spot behind "a stereo clip through any core insert came out
    // mono": both implementations can agree perfectly on the left channel
    // while one of them never fills the right.
    const stereo = onDisk.cases.filter((entry) => entry.firstR !== undefined);
    expect(stereo.length).toBeGreaterThan(20);
    for (const entry of stereo) {
      expect(entry.lastR, `${entry.name} has firstR but no lastR`).toBeDefined();
      expect(entry.firstR).toHaveLength(onDisk.frames);
      expect(entry.lastR).toHaveLength(onDisk.frames);
    }
  });
});
